[Journal]
Storage=persistent
Compress=yes
SystemMaxUse=128M
RuntimeMaxUse=32M
SystemKeepFree=512M
RuntimeKeepFree=64M
SystemMaxFileSize=8M
RuntimeMaxFileSize=4M
SystemMaxFiles=32
RuntimeMaxFiles=8
MaxFileSec=1day
MaxRetentionSec=14day
